### ISSUE TITLE
FX Effects doesn't carry to .vox file properly

### ISSUE THREAD

**Issue by UMRPL** [SirusDoma/VoxCharger#2]
FX Effects doesn't work at all in-game - they are just blank.
Looked at .vox file - data in-fact carries but probably not properly.
Noticed that this appears in each chart:

![image](https://user-images.githubusercontent.com/36577699/155338214-d6ce14db-59ba-4582-b8f0-e8997be08281.png)

There are two comas after 6 - probably it shouldn't happen. It doesn't happen in original sdvx .vox charts.

Tried charts created in newest and oldest ksm charts. Still not working.

**Comment by UMRPL** [comment]
Looked around - 6 is identifier for wobble effect - from what I see wobble effects aren't converting properly to .vox yet because of lacking parameters. Same with lowpass. But that causes breaking rest of sounds effects so they doesn't work.

**Comment by SirusDoma** [comment]
Fixed this issue, feel free to re-open the issue if this still happening in the latest release
